events {}

http {
    upstream workers {
        server worker:9000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://workers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}